### ISSUE TITLE
The city name is still not showing 

### ISSUE THREAD

**Issue by Floraachr** [NeuroDevCo/babylab-redcap#17]
I know I already made a comment about it but: 

When I put the name of the city in the participant file, shouldn't it be showing? 
I we don't put anything that's fine, but once it's written it should be showing when we want to take a look at the participant's infos, no? 

Here's an example for Rick: I put that this baby lives in Paris , then submit, and when I take a look there's no info on the city cell 
![image](https://github.com/user-attachments/assets/a40bca47-ed35-419a-ba01-24d5c2ffe25b)
<img width="777" alt="image" src="https://github.com/user-attachments/assets/3d952cc6-9f77-404a-a6b5-960bcc00ac9b">

**Comment by gongcastro** [comment]
Fixed in #5be332b.
